name: my_first_CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: setting up all python versions
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Instolation of needed files
        run: pip install -r requirements.txt
      - name: run tests
        run: python -m unittest discover .
        
